### ISSUE TITLE
Replace PostScribe in the PUC

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-mobile-ios#1018]
The Prebid Universal Creative has been using the [PostScribe](https://github.com/krux/postscribe) library for rendering in mobile for many years. PostScribe is deprecated. 

This is the relevant code in the PUC is https://github.com/prebid/prebid-universal-creative/blob/master/src/postscribeRender.js

We need someone who understands mobile webviews to step up and help Prebid figure out what's going on here.

Options: 

1. PostScribe was a nice-to-have that we can live without. Just remove it from the PUC and write directly to the iframe body with javascript.
2. No, webviews really do need an asyncronous way to write or it will negatively impact the user experience. We need to update the PUC to replace PostScribe with ____.

@alexsavelyev - please discuss with the mobile committee, which owns this part of the PUC.

**Comment by justadreamer** [comment]
I think we need to carefully consider option 2, but not from the mobile native webviews perspective.  Mobile native webviews can do synchronous writes and it would not impact the user experience or performance, because:
- there is nothing else to render in an ad webview in a native mobile app anyway - so no content we are preventing with a synchronous write
- on modern mobile OSes rendering runs out-of-process and on older mobile OSes it runs on a separate thread in-process - so not impacting the performance of the outside app

However asynchronous writing might be needed for AMP, because it seems to be also relying on [writeAdHtml](https://github.com/prebid/prebid-universal-creative/blob/1c32e8bec4afde457dcf4af99312ecca998030fd/src/mobileAndAmpRender.js#L149) call imported from [postscribeRender.js](https://github.com/prebid/prebid-universal-creative/blob/1c32e8bec4afde457dcf4af99312ecca998030fd/src/postscribeRender.js).  There it might have an impact on user experience - for it might delay some other content rendering.  However can't comment deeper on AMP due to a lack of expertise. 

So it may be the case that for mobile we can just do a synchronous write, while for amp we'd still need to seek another solution - further code bifurcation..

**Comment by bretg** [comment]
Thanks for moving this forward @justadreamer. I'd say it would be fine to use a different write routine in the PUC for mobile-vs-AMP.

I rather doubt anyone's going to step up and offer to fix AMP rendering for us. Seems to be a decaying platform. If mobile doesn't need async writes, we should divorce them from PostScribe.
