### ISSUE TITLE
Local Cache storage issue + React native crash

### ISSUE THREAD

**Issue by AntoineJac** [prebid/prebid-mobile-ios#103]
Hi team,

There are a few issues with current iOS code:
1- no possibility to use the local caching instead of server caching
2- when forcing and testing local caching, many time KV are passed but not line items is displayed as the local storage hasn't cache the creative when the line is trying to call it.
3- High % of crash in React as the UA is relying on having main thread active which is not the case with react native.
4- WebView is being deprecated and some alert has raised (future issue as still supported in ios12)

Here is the PR with all the fix for the 3 third points. 

https://github.com/prebid/prebid-mobile-ios/pull/102

This issue has been flagged with Appnexus for a long time and we may force to create our own version as several clients are impacted or blocked because of it...

@mjacobsonny and @ppuviarasu , can you please have a look and review it.

Thanks,

**Comment by mjacobsonny** [comment]
@AntoineJac 

It looks like this PR is combining bug fixes with a new feature request (support for local caching).  Would it be possible to open a separate PR which just addresses the bug fixes mentioned above?  Then, separately, we can evaluate the need to support local caching as a new feature.

**Comment by AntoineJac** [comment]
+ @bretg our product manager who can evaluate with you the local caching.
Please notice that it was a feature support in previous SDK version (still support in Android) that has been removed without notice on the ios SDK...

**Comment by bretg** [comment]
@mjacobsonny - it's possible to view the support of local caching as a bug fix, since it was there previously and removed without recourse.

If there are specific suggestions about the mechanism for defining the cache behavior, I'm sure Antoine will address that. But unless it will significantly help the PR review, question the need to split the PR.

**Comment by mjacobsonny** [comment]
@bretg -- I don't view this as a breaking change/ bug fix, since it does not alter any user-facing behavior or APIs.  Removing support for local caching was a design decision, based on substantial confusion and SDK instability that it caused.  I do not want to add it back without thorough definition of use-cases and cost-benefit analysis based on the extra complexity that would be added to Prebid Mobile.

**Comment by AntoineJac** [comment]
@mjacobsonny , here is the PR for the bug fix only, if you can have someone review it soon as it makes React Native crash:
https://github.com/prebid/prebid-mobile-ios/pull/108

I let you discuss the local caching but I would strongly recommend it, especially in geos where connections is slow. The PR is normally fixing all caching issue.

**Comment by ppuviarasu** [comment]
We have released the bug fix as part of #0.5.2
Can we create a new Issue for local cache & discuss it there...
