### ISSUE TITLE
Actual screen size for Interstitial format 

### ISSUE THREAD

**Issue by yoalex5** [prebid/prebid-mobile-ios#154]
Could you please explain why InterstitialAdUnit use a real screen size instead of predefined sizes(as previous API ) ?

Thank you

**Comment by ppuviarasu** [comment]
Thats the new definition for the interstitial ad format. Instead of the predefined sizes we send in the screen size to the prebid server which in turn calculates 50% of the width & height & renders ads that are more than the defined criteria.
This actually removes the hard coding of sizes and the issue that we had earlier were 320x50 was always served though we had 300x250 creatives for the line item. The pick was more for 320x50 than 300x250. This logic would solve the issue
