### ISSUE TITLE
UIWebView is deprecated, needs to be removed before the end of 2020 for updates and the end of April for new apps

### ISSUE THREAD

**Issue by sareninden** [prebid/prebid-mobile-ios#286]
**Describe the bug**
Apple will stop submission of new apps per the end of April 2020 for new Apps.
For updates it is allowed till the end of December 2020.

**To Reproduce**
* Submit an app to the appstore with this library included
* Apple will sent you a warning about the deprecation of UIWebView

**Expected behavior**
The library is compatible with new apps per April 2020.
A pod subspec could for example allow users to keep using UIWebView related items if needed till the end of 2020.

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: iOS
 - Version 9+

**Smartphone (please complete the following information):**
 - Device: Any iPhone or iPad
 - OS: iOS 9.0+

**Additional context**
The class `AdViewUtils` uses the UIWebView.

**Comment by bszekely1** [comment]
Hi @sareninden, this issue is already being addressed and is linked to this issue: https://github.com/prebid/prebid-mobile-ios/pull/284

This is a known problem for some time, however the wait was or Google Ad Manager to support WKWebView. Now there is support we picked up the project again with the above PR.
