### ISSUE TITLE
Issue for apps built with Xcode 12: `isAdvertisingTrackingEnabled`

### ISSUE THREAD

**Issue by craigomac** [prebid/prebid-mobile-ios#325]
**Describe the bug**
On apps built with Xcode 12, `isAdvertisingTrackingEnabled` now always returns `false`. That means the only reliable way to determine if tracking should occur, outside of using the new `AppTrackingTransparency` framework (which is iOS 14 only) is to fetch the IDFA and confirm that it doesn't consist only of 0s and "-" (i.e. the "zero UUID").

Initially reported here: https://twitter.com/jon_schlegel/status/1306224934037917696. In subsequent investigations we found that this wasn't an iOS 14-only issue, but affected the app on any iOS version built with Xcode 12.

**Expected behavior**
When the IDFA is available (regardless of what `isAdvertisingTrackingEnabled` returns), the value used in `lmt` in the SDK should indicate that tracking can occur.

**Smartphone (please complete the following information):**
 - Device: any iOS device
 - OS: Any iOS version, if app was built with Xcode 12

**Additional context**

**Comment by bszekely1** [comment]
Hi @craigomac,

Yes, i was able to replicate the problem. We just released Prebid SDK 1.8 today. We should release a 1.8.1 to address this concern.

Since [isAdvertisingTrackingEnabled](https://developer.apple.com/documentation/adsupport/asidentifiermanager/1614148-isadvertisingtrackingenabled) is being deprecated in favor of the app transparency framework in iOS14+, we cannot simply ignore the field on pre-iOS14 devices. User should be able to opt out in both pre and post iOS14.

Below is the App Tracking Transparency framework today:

ATT Status | Description | Example IDFA |
------------ | ------------- | ------------ |
0 | not deterined | C5D6A97A-70EF-4A07-9A42-59E2584B214A |
1 | restricted | 00000000-0000-0000-0000-000000000000 |
2 | denied | 00000000-0000-0000-0000-000000000000 |
3 | authorized | C5D6A97A-70EF-4A07-9A42-59E2584B214A |

This is how it will look in the future in 2021 when IDFA is suppressed:

ATT Status | Description | Example IDFA |
------------ | ------------- | ------------ |
0 | not deterined | 00000000-0000-0000-0000-000000000000 |
1 | restricted | 00000000-0000-0000-0000-000000000000 |
2 | denied | 00000000-0000-0000-0000-000000000000 |
3 | authorized | C5D6A97A-70EF-4A07-9A42-59E2584B214A |


I would like to propose the following logic in psuedo code:

```
If(iOS version >= 14)
{
	setATTS = ATTrackingManager.AuthorizationStatus
	setIDF = "IDFA_value"
}
else
{
	if(!ASIdentifierManager.shared().isAdvertisingTrackingEnabled)
	    lmt = true;

    setIDFA = "IDFA_value"
}

fetchDemand () {
	if(lmt)
		passLMT //passes LMT to PBS in device.lmt

	if(ATTS) //pass ATTS status to PBS in device.ext.atts
		passATTS

	passIDFA  //passes IDFA whatever the value is in device.idfa
}
```

Some of my recommendations above are based on the following:

- `lmt` will be deprecated in iOS14 and no use using it
- IAB has defined to pass atts status in [device.ext.atts](https://github.com/InteractiveAdvertisingBureau/openrtb/blob/669b94ff1172b5347abed95cc02cfb9db9f82ad9/extensions/community_extensions/skadnetwork.md#device-extension)
- Let Apple decide when IDFA is available and pass whatever value Apple provides
    - If GDPR applies, Prebid Server should suppress the IDFA and pass DNT signaling to the DSPs not to track
- In scenarios where an app is built with Xcode12 and the device's firmware is pre-IOS14, if Apple provides the IDFA, we pass what we have


Would like to have your feedback.

**Comment by craigomac** [comment]
It looks okay, though I wonder about this part:

	if(!ASIdentifierManager.shared().isAdvertisingTrackingEnabled)
	    lmt = true;

On pre-iOS 14 devices running apps built with Xcode 12, `lmt` will then always be `true`. Does that then reflect a change in behaviour for advertising partners?

**Comment by bszekely1** [comment]
I just tested building the Prebid Demo app with Xcode version 12.0 (940.16) and lmt works as expected. By default the lmt flag is off as seen in the call to Prebid Server. If you enable it, the lmt flag is passed as 1. It's possible you were testing in a beta version that was older than my current version. Because Xcode is in Beta, different versions may have different behavior.

Regardless the one i tested was the latest, lets assume that the use case you describe is an edge case and will likely be resolved once people upgrade to iOS 14.

**Comment by bszekely1** [comment]
@craigomac We are releasing Prebid SDK 1.8.1 Thursday for iOS 14 support.
