### ISSUE TITLE
LMT not deprecated in 14.x

### ISSUE THREAD

**Issue by bszekely1** [prebid/prebid-mobile-ios#348]
**Describe the bug**
Apple has incorrectly deprecated LMT in iOS versions 14.0 and 14.1 potentially causing revenue impacts for bid adapters who incorrectly read the `lmt` signal for iOS versions 14.x.

The difficulty here is that Apple has poorly deprecated the usage of `lmt` by setting `lmt=1` for all traffic in iOS versions 14.0 and 14.1. This was corrected in iOS versions 14.2+ where `lmt=0` by default unless an explicit signal of `ATTS=1 or 2` is set by the user, whereby `lmt` would be set to 1 if not authorized or denied.

The current behavior of Prebid SDK is to suppress `lmt` from being passed to Prebid Server in iOS versions 14.x+, leaving the Apple bug unimpacted in Prebid SDK or Prebid Server.

Going forward, in iOS versions 14.x+, bid adpters should read the ATTS signal and use LMT accordingly as recommended by OpenRTB:

-  "DNT" or "LMT" = 1 when "ATTS" = 0,1,2
- "LMT" or "DNT" = 0 when "ATTS"= 3

no further action is required here. This will remain for informational purposes. No further action is required here in Prebid SDK or Prebid Server.

**Comment by YuriyVelichkoPI** [comment]
I think that SDK has to send ‘lmt’ in as many cases as it can be determined and doesn’t delegate this to adapters or demand-side logic.  

I’ve experimented with iOS 14.0.1 and found out that despite constant value 1 for isAdvertisingTrackingEnabled the IDFA changes according to the flag in Settings -> Privacy -> Tracking -> Allow Apps to Request to Track. I believe that it could be used for the determination of `lmt`.

Since the bug in iOS is defined we can wrap it up. 
My suggestion is:

iOS < 14:
```
lmt = !ASIdentifierManager.sharedManager.isAdvertisingTrackingEnabled
```

iOS >= 14

If Authorization Status is defined send lmt according to the IAB spec.

If Authorization Status is not defined 

```
lmt = idfa == @”00000000-0000-0000-0000-000000000000”.
```

According to this SDK will send the `lmt` according to IAB specs in all cases, even when ATTS becomes mandatory. And when it becomes the logic can be clarified with a particular SDK version 

Thoughts?

**Comment by bszekely1** [comment]
The behavior of `lmt` is corrected in iOS 14.2 and above, however Limit Ad Tracking being removed from the UI and is being replaced with ATTS as the explicit opt-out signal. It remains unpredictable what Apple will be doing with `LMT` in the future and I am less inclined to make such static changes in Prebid SDK for the following reasons:

- Prebid SDK 1.8, 1.81 and 1.9 have been released into the wild with it's existing behavior. Many users will be in this state for a long period of time have a mixed mode support of `LMT`. If bid adapters don't make this change they may be in violation of not having an opt out. If they make the change in PBS then we are good and can leave the settings as is because we may have to support this way for some time 
- I am really not a fan of using a signal against it's intended purpose. IDFA is not meant to be used as a signal for limiting ad tracking, this is bad development practice to use this especially considering we do not control the signal itself, Apple does
- There are various levels of privacy that include government regulation and self imposed industry ones, if we use LMT here when there is no IDFA, we are sending an explicit signal that the user opted out when other scenarios may apply, i don't like the idea of pigeon holing ourselves. 
- Lastly, I am really not keen on making such SDK changes that are so fragile and important to the business when behaviors change. It's much easier to change bid adapter behavior in PBS where the change is instant than to change anything in the SDK.

**Comment by YuriyVelichkoPI** [comment]
I’m not sure that the `lmt` in rtb has to be set exclusively with `isAdvertisingTrackingEnabled`. The `lmt` should indicate the tracking limitation for the particular user, but not be limited by the `isAdvertisingTrackingEnabled` flag. 

Because the `isAdvertisingTrackingEnabled` is deprecated we should not rely on it. It is true. But ATTS provides new OS properties for determining the ad tracking limitations. And they should be used to determine the `lmt` in bid requests. 

On the other hand, it is not clear whether demand partners have changed their algorithms to determine `lmt` according to the  ATTS attribute or they are supposed to get the `lmt` from the client. And I’m afraid that according to [the IAB spec](https://github.com/InteractiveAdvertisingBureau/openrtb/blob/master/extensions/community_extensions/skadnetwork.md#dnt-lmt-and-app-tracking-transparency-guidance) buyers don't expect that they have to calculate `lmt` by themselves. I think we can’t predict it and it would be better to ask in the skadnetwork channel, there are a lot of buyers there. 

From my perspective, the `lmt` is a pretty significant property for the buyers. Probably the auctions heavily depend on it. If the `lmt` is absent, the priority of the bid could be lower in the internal auction. And most probably that no one has adopted their traffic quality policies to ATTS so fast. That's why I think that it is important to send it out. Also, if the `lmt` is really important, the single change in the SDK will be more efficient than dozens of changes in adapters.

I don’t support such workarounds as well. Need to keep logic as clear as possible and use things according to their purpose. But in this particular case, we are trying to wrap the third party bug and the proposed approach defines the condition for Limit Ad Tracking is pretty accurate. Since Apple is going to make ATTS obligatory starting from the upcoming beta, the `lmt` will be set according to the user consents for all new application versions.

**Comment by bszekely1** [comment]
After further reflection and analysis of the problem, compounded by the difficulty of having every adapter change their logic, it is reasonable to make this change as soon as possible. Yes, keying off the IDFA is extremely sub-optimal but i would recommend we do this only for iOS versions up until Apple releases their final version to mandate pubs use ATT. From there we can impose the following logic on a subsequent release:

- "DNT" or "LMT" = 1 when "ATTS" = 0,1,2
- "LMT" or "DNT" = 0 when "ATTS"= 3

thoughts?  By the way, i am not super jazzed about doing iOS specific version behaviors but it is what is it is. I don't see us using IDFA as an LMT signal once Apple is firm on their usage of ATTS.

**Comment by YuriyVelichkoPI** [comment]
sounds reasonable to me.
