### ISSUE TITLE
Location Manager

### ISSUE THREAD

**Issue by yoalex5** [prebid/prebid-mobile-ios#349]
## Type of issue
Location Manager

## Description
Prebid  SDK uses custom internal implementation of LocationManager for setting a location(lat, lon)
 - iOS uses `kCLDistanceFilterNone` for distanceFilter and `kCLLocationAccuracyKilometer` for  desiredAccuracy
 - Android  `getLastKnownLocation` method

As you see we have several issues:
1. iOS and Android use different logic 
2. Some publishers want to have more control (#336)

## Goals
1. Align API
2. Allow publisher set precision on location that the Prebid SDK passes to bidders

**Comment by YuriyVelichkoPI** [comment]
Location is a pretty sensitive property of rtb. It influences not only on selecting a winning ad but also helps identify users better. Therefore, it should be as precise as possible in each bid request. It is not a simple task. The solution should take into consideration several factors:
- Resources consuming
- Ad unit kind (with autorefresh or without)
- Behavior in the background 
- Dependencies on other apps which updates, or don’t update location
- The platform-specific implementation of the internal location managers

I wouldn’t delegate these to publishers. Nobody really thinks about the needs of ad SDKs. It is better to develop a proper approach and implement it on both platforms. 

The current Android implementation does not consume system resources at all but provides potentially outdated location value.

The iOS is requests resources often. For the first step, we just need to change the filter value from kCLDistanceFilterNone to some particular value, for example, to 50 (meters). The accuracy could be reduced either, for example to kCLLocationAccuracyHundredMeters. 

Further, it makes sense to develop a single algorithm for the LocationMager and implement it in the same way on both platforms. But still without giving publishers a lot of leverages in order to provide the most accurate location value in bid requests.

**Comment by stevemummey** [comment]
Hi, @yoalex5

I'd like to the team reconsider Goal 2, "Allow publisher set precision on location that the Prebid SDK passes to bidders" from this issue. We as a pub feel it's necessary to have control over the precision given the privacy risks lie with the pub when it comes to location.  I do understand and appreciate @YuriyVelichkoPI 's points about the needs of the SDKs however we feel the risks assumed by the pub outweigh the needs for an advertiser needing to know I'm in my kitchen. ;)

If this has already been resolved, please let me know.  Both our iOS and Android dev teams have tried to reduce the precision of location being passed but could not find any solutions. Could be that we simply missed it.

Many thanks all!
