### ISSUE TITLE
Support  fastlane

### ISSUE THREAD

**Issue by yoalex5** [prebid/prebid-mobile-ios#367]
What do you think about [Fastlane tools](https://fastlane.tools/) for delivering iOS and Android SDK?
[Fastlane GitHub page](https://github.com/fastlane/fastlane)

**Comment by ppuviarasu** [comment]
few questions to that you need to answer
1. Why do we need this? Prebid is an SDK that is integrated into any client apps. So we are not doing any deployment per say.
2. Does this do the uploading of SDK to maven & cocoapods
3. The docs talk about deploying to appstore & creating an alpha & beta test build.

What benefit are we thinking here to bring in this tool?

**Comment by YuriyVelichkoOpenX** [comment]
Hi @ppuviarasu , 

This question arose from OpenX's initiative about adding the rendering functionality to the Prebid SDK by migrating the codebase of internal SDK into the prebid. And we use Fastlane here to run all CI/CD pipelines.

Since SDK has rendering functionality it should be tested on real devices. And we have a bunch of smoke tests for running on real devices. So we use Fastlane to sign the AdHoc builds and upload them to the Firebase for manual QA testing. 

The multi_scan is one more helpful feature that we use to improve the sustainability of PR tests. It allows rerunning failed tests.

Other features that make build scripts better are:
- scan
- zip
- cocoapods (for build and run UI tests, not for deploying)
- slack

Right now we don't use Fastlane to push podspecs but we can do it using  https://docs.fastlane.tools/actions/pod_push/

**Comment by ppuviarasu** [comment]
The push to cocoapods & slack the release sounds interesting...

**Comment by bszekely1** [comment]
Closing this issue. This feature will be introduced with the rendering module.
