### ISSUE TITLE
Open Measurement Certification

### ISSUE THREAD

**Issue by YuriyVelichkoOpenX** [prebid/prebid-mobile-ios#394]
# Motivation

The PrebidMobileRendering framework supports Open Measurement (OM). It includes the Prebid's version of OM SDK and implements requirements for all ad formats. 

Now it is time to pass verification and become certified partner.

# Objectives 

In the scope of getting certification, we have to:

* Create demo applications for iOS and Android with needed ad formats
* Obtain a provisioning profile for the iOS app
* Verify that all needed events are triggered according to the OMID requirements
* Start the conversion with IAB about verification
* Submit applications to IAB
* Apply corrections if needed
* Get a certification label
* Update docs
 
## Demo Application

To get the IAB certification for Open Measurement, we have to submit the demo applications with target ad formats.

Since the certification must be renewed each year, it makes sense to introduce the standalone app with a distinct set of ad units and submit it each time. The Prebid SDK and OM SDK should be updated before each submission. 

OM SDK measures the rendering of creatives. Hence, for the verification, we have to submit only In-App integration cases. There is no need to verify GAM and MoPub integrations since the same engine performs rendering in all cases, and OM events will be identical.

The objectives for application deelopment are:

* Create a new Application for IAB certification
* Use only In-App Bidding integration cases
* Use the same UI as for the Internal test Application. A plain list of cases with corresponding ad views.
* Update the OM SDK to the last version.
* Add cases for certification: 
    * Banner (with scroll) 
    * MRAID resize
    * Opt-In Video With End Card
    * Display Native in feed
    * Native Video in the feed 
* Check OM events with Charles 

## iOS Provisioning profile

In order to ship the app to IAB, we have to sign it with an Ad-Hoc provisioning certificate. 

The objectives for creating an ad-hoc build are:

* Figure out if Prebid.org has an App Store account. 
* If it doesn't have - figure out which account we need to use - Prebid (create a new one), OpenX, Magnite, IX ... ?
* Prepare the provisioning profile for Ad-Hoc build with given device IDs (IAB will send them among certification papers).
* Prepare the .ipa artifact

# References

* [Landing page](https://iabtechlab.com/standards/open-measurement-sdk) 
* [Onboarding Guide](https://s3-us-west-2.amazonaws.com/omsdk-files/docs/Open+Measurement+SDK+Onboarding_version_1.2.pdf) 
* [Compliance Guide](https://omsdk-files.s3-us-west-2.amazonaws.com/docs/Integration%2BValidation%2BCompliance%2BGuide.pdf)
* [Quick Start Guide](https://omsdk-files.s3-us-west-2.amazonaws.com/docs/IABTechLab_OMSDK_Quick_Start_Onboarding_Process_2019-12.pdf)
* [OMID API](https://s3-us-west-2.amazonaws.com/omsdk-files/docs/OMID_API_v1.2.pdf)
* [Integration iOS](https://interactiveadvertisingbureau.github.io/Open-Measurement-SDKiOS/)
* [Integration Android](https://interactiveadvertisingbureau.github.io/Open-Measurement-SDKAndroid/)

**Comment by ChrisHuie** [comment]
Connecting with publishers that have worked out certification and following up on best path forward for publishers to make sure they are getting viewability that reflects ad.

**Comment by YuriyVelichkoPI** [comment]
I've double-checked the IAB compliance list: https://complianceomsdkapi.iabtechlab.com/compliance/latest

And looks like NewsBreak really certified the prebid SDK under their brand: 

iOS: 
```
    {
      "certificationStatus": "Active",
      "certificationProcess": "2",
      "lastCertifiedDate": 20230519,
      "lastUpdateDate": 20230519,
      "libraryVersion": "1.4.4",
      "partnerVersion": "5.0",
      "platform": "iOS",
      "companyName": "Particle Media",
      "partnerName": "Newsbreak1",
      "appName": "NewsBreak SDK",
      "certifications": [
        {
          "creativeType": "htmlDisplay",
          "adSessionType": [
            "html"
          ]
        }
      ]
    },
```

Android: 

```
 {
      "certificationStatus": "Active",
      "certificationProcess": "2",
      "lastCertifiedDate": 20230519,
      "lastUpdateDate": 20230519,
      "libraryVersion": "1.4.4",
      "partnerVersion": "2.0.3",
      "platform": "Android",
      "companyName": "Particle Media",
      "partnerName": "Newsbreak1",
      "appName": "NewsBreak SDK",
      "certifications": [
        {
          "creativeType": "htmlDisplay",
          "adSessionType": [
            "html"
          ]
        }
      ]
    },
```

I assume that is Prebid SDK because of the [bug](https://github.com/prebid/prebid-mobile-ios/issues/879) related to the `partnerVersion` on iOS. 

I'm not sure whether it is the correct approach if each publisher will have to certify the same SDK over and over again. 

On the other hand, the Prebid SDK is an open-source SDK, so anyone can change its behavior but still send "verified" OM signals.

**Comment by BaiShuoyang** [comment]
We have recently successfully gone through the OM certification for our IOS SDK (which is based on Prebid IOS SDK Rendering API). Noting down some findings:

1. If the integration partner is using Prebid SDK and wants to be certified under the integration partner's own namespace, the integration partner needs to replace the omsdk-v1.js used in the xcode framework with the omsdk-v1.js from omsdk-js-1.x.x.zip downloaded in https://tools.iabtechlab.com/omsdk (generated using the integration partner’s own namespace). Otherwise the partnerName parameter in the sessionStart event triggered by the OM verification script will not be the namespace of the integration partner. The default partnerName of Prebid Mobile IOS SDK is "Prebidorg".

![image](https://github.com/prebid/prebid-mobile-ios/assets/7251653/270a373e-de10-42e9-98fc-5afe1d4abe98)

2. At the beginning of the OM certification process, the integration partner needs to reach out to IAB Tech Lab to get the verification JS script. The verification script then needs to be inserted into integration partner’s test ad creatives, and the test ad creatives need to be served into the integration partner’s test app for IABTL team’s testing. Tech Lab Compliance team will then execute the validation test cases and compile the results. If everything is good, the OM certification is done and the verification results should be shown in OM SDK logs: https://complianceomsdkapi.iabtechlab.com/compliance/latest. 


For Prebid Mobile, if we are hoping that any publishers or partners using Prebid Mobile Rendering API are OM certified by default and they do not mind the OM namespace is Prebidorg (instead of their own organization name), we should consider going through the OM certification with IAB Tech Lab with our Prebid Mobile demo app, and the end results should be that Prebidorg becomes a certified partner for both Android and iOS listed in https://complianceomsdkapi.iabtechlab.com/compliance/latest.

**Comment by YuriyVelichkoPI** [comment]
I would add that if Prebid SDK is not certified and Prebid encourages publishers to certify their integration, the way OM support should be changed.

1. Prebid SDK shouldn't contain any OM artifacts. No .js, no OM SDK itself.
2. Prebid SDK should provide an interface to plug in the publisher's OM artifacts instead.


The current implementation doesn't assume publisher-based certification and, as a result - it is incorrect.

On the other hand, if Prebid decides to pass certification, the open source nature of the library will open the door for counterfeiting the OM signals. The source code of the SDK can be changed in a way that OM signals will be incorrect. They will be certified, though.

To avoid such opportunity, the Prebid SDK + OM should be shipped in the binary form so measurement and demand partners can be sure that the SDK codes kept untouched by the app developers. And as a result the signals contain correct measurement data.

The SDK itself can still be open-sourced. However, the OM addendum should be closed-sourced and private. So, the publishers can't build the Prebid SDK with Prebid's OM on the local machines. The open-source version of Prebid SDK will be shipped without integrated OM. Any publisher can plug in their OM SDK, or use the prebid SDK without OM, for example for Original API or for integration with their own SDK.

So, in any case, we should rebuild the OM support in a plug-in way.

**Comment by bretg** [comment]
What's the status on this? Did the committee decide to split out OM support or have Prebid get certification?

**Comment by bretg** [comment]
Now there's a FAQ entry on Open Measurement - https://docs.prebid.org/faq/prebid-mobile-faq.html#is-prebid-certified-for-the-open-measurement-sdk

**Comment by YuriyVelichkoPI** [comment]
@bretg, @alexsavelyev, @mmullin

This issue can be closed since the committee developed and stated the OM supporting approach. And the FAQ page highlights the position correctly.

However, I would like to draw your attention to the following technical aspect that is worth considering. 

IAB provides a special version of the OM SDK to each vendor. The OM is shipped as a precompiled binary. Moreover, each distribution differs at least by API. For example, the OM classes for Prebid have special prefixes (iOS) or are placed in special modules (Android):

Android: `com.iab.omid.library.prebidorg.utils`
iOS: `OMIDPrebidorgAdSession`

Therefore, publishers integrating the Prebid SDK integrate Prebid's version (binary) of the Open Measurement.

I don't see big problems here. However, since Prebid delegates the OM certification to publishers, making them OMID vendors, I think we should implement the mechanism to utilize the custom (publisher's) OM library in the Prebid SDK. So the publisher can^ 
 - register yourself on the IAB site (become an OMID vendor)
 - order the OM library (IAB portal will build a special OM SDK framework)
 - plug it into the Prebid SDK 
 - pass certification for its configuration. 

This approach will be much more transparent from an ownership perspective. The Prebid SDK can continue to use its own version of OM SDK by default, but publishers who want to use their own IAB framework will have the ability to customize the Prebid SDK accordingly.

If you think that it makes sense, I can create a task to rearchitect the integration of OM SDK in order to support custom binaries. 

It can be done in a separate scope. This task can be closed.
