### ISSUE TITLE
Support native-banner ads

### ISSUE THREAD

**Issue by congnd** [prebid/prebid-mobile-ios#427]
**Is your feature request related to a problem? Please describe.**
We are currently using banner-native ads and would like to ask if Prebid can support this type of ad.

About banner-native ads: https://developers.google.com/ad-manager/mobile-ads-sdk/ios/native-banner

**Describe the solution you'd like**
Support banner-native ads

**Describe alternatives you've considered**
It looks like I can use the provided implementation (https://docs.prebid.org/prebid-mobile/pbm-api/ios/pbm-banneradunit-ios.html) of Banner Ad for the banner-native ad as well but I'm not sure if it is the official way to do it. Furthermore, the banner resizing logic that is recommended by the SDK does not work as expected. My current resizing logic looks like below:

```Swift
public func adLoader(_ adLoader: GADAdLoader, didReceive bannerView: GAMBannerView) {
        AdViewUtils.findPrebidCreativeSize(
            bannerView,
            success: { size in
                bannerView.resize(GADAdSizeFromCGSize(size))
            },
            failure: { error in
                print("GAM prebid error: \(error)")
            }
        )

    // Add bannerView into the view hierarchy
}
```

With the above setup, I don't see any ad content even it seems that the ad is there on the view hierarchy. It's all white color.

**Comment by YuriyVelichkoPI** [comment]
Hi @congnd ! The approach described in the docs is official. 

I'm not sure about the resizing, since it depends on multiple factors of particular integration. 

About displaying the loaded ad I can  give  you  two suggestions for debugging
- make sure that the bid request won a native ad (use proxy and verify the bid response)
- make sure that you  set up the creative for the native ad properly according to this guide
https://docs.prebid.org/adops/gam-native.html#3-style-your-native-ad

Also, you can attach a test project with a reproducible case and we can help with troubleshooting.

**Comment by congnd** [comment]
Hi @YuriyVelichkoPI 
Thanks for the response. 
Actually, the problem was about the banner ad which is loaded through a loader (`GADAdLoader`) but your advice just gave me a big hint. After looking at the network log, I realized that I was using the wrong configuration which causes the bit request to return an error. and that's it. Again, thanks a lot for your help.
