### ISSUE TITLE
Info.plist bundle short version is wrong

### ISSUE THREAD

**Issue by ThomWee** [prebid/prebid-mobile-ios#514]
**Describe the bug**
The SDK version which is send alongside a request for bids always send as SDK version the text "1.0" This is not true since we already have a version 1.12.1 as stable available.

**To Reproduce**
1. Build a test app using latest Prebid Mobile SDK
2. Run the app and trigger a bid request
3. Check the request which is send. The JSON object under **app.ext.prebid** contains two entries. The source and version.

**Expected behavior**
A new SDK should also send this detail within its JSON request.

**Screenshots**
![image](https://user-images.githubusercontent.com/4629834/152177177-638a774d-708b-4376-b039-d6a08ed18fb1.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: 15.3
 - Native App
 - SDK Version 1.12.1

**Comment by OlenaPostindustria** [comment]
Hi, @ThomWee!
I've checked our test demo app and made a brand new application, where PrebidMobile was integrated using Cocoapods. In both applications I see bid request **app.ext.prebid** object, that contains a stable PrebidMobile version: 
<img width="318" alt="image" src="https://user-images.githubusercontent.com/92721590/153588479-0d397bd4-3b2a-4d49-bdf2-da67f00df006.png">
Could you, please, provide us with an app example, where the bug is reproduced?

**Comment by ThomWee** [comment]
@OlenaPostindustria I'm using PrebidMobile via SPM. I'll prepare an app example this week.

**Comment by OlenaPostindustria** [comment]
@ThomWee
I've reproduced this issue by integrating PrebidMobile via SPM. We'll try to solve this problem.

**Comment by ThomWee** [comment]
Awesome. Thanks for letting me know. 👍
