### ISSUE TITLE
Fix app crash: AdMob Native Ad

### ISSUE THREAD

**Issue by OlenaPostindustria** [prebid/prebid-mobile-ios#516]
**To Reproduce**
1. Run Internal Test App.
2. Choose Native and AdMob sections on the main page.
3. Choose any item from the proposed list of examples.
4. See app crash in PrebidAdMobNativeViewController with message: `Thread 1: Precondition failed: NSArray element failed to match the Swift Array Element type. Expected GADNativeAdImage but found GADNativeAdImage`.

**Screenshots**
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/92721590/152523285-23f3ae86-880b-4918-ab2f-d39285c1ad55.png">

**Comment by YuriyVelichkoPI** [comment]
We can't fix this error in a clean and reliable way. 

In order to avoid it, publishers will have to integrate the adapters using the source code. In this case, objects will be created in the same bundle and will have the same type from the obj-c runtime perspective.  

The respective warning will be added to the integration documentation.
