### ISSUE TITLE
Request data inconsistency between iOS and Android

### ISSUE THREAD

**Issue by mfitzek** [prebid/prebid-mobile-ios#687]
Hello,
we found an inconsistency between iOS and Android in the request.

Targeting context data set by `Targeting.shared.addContextData` in iOS are nested in `prebid` property.

iOS request:
```json
"app": {
    "ext": {
      "prebid": {
        "data": {
          "iosYlSdkVersion": [
            "9.3.0"
          ]
        },
        "source": "prebid-mobile",
        "version": "2.0.3"
      }
    }
  }
```

Android request:
```json
  "app": {
    "ext": {
      "data": {
        "androidYlSdkVersion": [
          "6.15.4"
        ]
      },
      "prebid": {
        "source": "prebid-mobile",
        "version": "2.0.3"
      }
    }
  }
```
It would be great, if those requests has the same structure, eg. for log analysis.

**Comment by marcelklinek** [comment]
Hi @OlenaPostindustria,

@mfitzek and I would like to submit a PR to fix this issue. The problem is we actually do not know what is the "correct" structure. I’m putting correct into quotes here because the OpenRTB spec does not specify the structure of content of the `ext` property.

Is this new structure we see in iOS client something you’d like to keep and actually fix the Android side of things?

Here are some links to source code which we think is relevant to the discussion

iOS:

https://github.com/prebid/prebid-mobile-ios/blob/master/PrebidMobile/PrebidMobileRendering/ORTB/PBMORTBApp.m#L68

Android:

https://github.com/prebid/prebid-mobile-android/blob/master/PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/networking/parameters/AppInfoParameterBuilder.java#L73

**Comment by bretg** [comment]
My perspective is that the android code base is correct here.

app.ext.prebid.{source,version} are defined in the [PBS endpoint doc](https://docs.prebid.org/prebid-server/endpoints/openrtb2/pbs-endpoint-auction.html).

app.ext.data{} is the First Party Data location. So assuming that iosYlSdkVersion is something that ads might want to target or be used in reporting, it belongs as FPD in app.ext.data{}, not app.ext.prebid.data{}

**Comment by marcelklinek** [comment]
Thanks for jumping in, @bretg
You have correctly guessed that we’d like to report on those properties.
So for me the takeaway is that does make sense to come up with a PR for iOS client. Did I get that right?

**Comment by bretg** [comment]
> make sense to come up with a PR for iOS client

that would be great - thanks!
