### ISSUE TITLE
Revise SDK GPP Support

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-mobile-ios#883]
The original spec for Prebid SDK support of GPP was incorrect.  The [IAB's CMP specification](https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/main/Core/CMP%20API%20Specification.md) defines different variables. Here's the proposed processing:

1. IABGPP_HDR_GppString - if this is present, pass to Prebid Server as regs.gpp. No validations.
1. IABGPP_GppSID - if this is present, it should be an underscore-separated set of integers. Parse and convert to an array of integers. Ignore any values that aren't integers, logging a warning if that's feasible in an SDK environment. No need to validate the specific integers within the array.

**Comment by YuriyVelichkoPI** [comment]
Hi @bretg ! Could you specify the case with the reporter since both SDK contains the code implementing the GPP in the way described in the ticket? 

Here is an Android [unit test](https://github.com/prebid/prebid-mobile-android/blob/f979d8f682d21544f933943a027c692c88dbfa4d/PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/networking/parameters/UserConsentParameterBuilderTest.java#L191) that checks that the string "2_3" will be converted into array [2,3] in the request. 

And here is a similar [unit test](https://github.com/prebid/prebid-mobile-ios/blob/a90adfd5b26b9d94531fee774c8d8fc63a378ae7/PrebidMobileTests/RenderingTests/Tests/ParameterBuilderTests/BasicParameterBuilderTest.swift#L349) for iOS. 

So we need to know what exactly goes wrong.

**Comment by bretg** [comment]
Will go back to the Pubmatic team

**Comment by pm-pritesh-lad** [comment]
Hi @bretg @YuriyVelichkoPI ,
The confusion was about how & where to handle the conversion from string to int array. With the details shared above it's clear now that the ad SDKs should read the values as per CMP spec & convert those into an int array while including in the RTB request.
Thanks for the clarification.

**Comment by YuriyVelichkoPI** [comment]
@bretg can we close this ticket?

**Comment by bretg** [comment]
Confirmed we can close this. Thanks.
